[package]
name = "valaddr_rs"
version = "0.1.0"
edition = "2024"
description = "Easy Validation of Either IP Addresses or Domains"
license = "MIT"
repository = "https://github.com/f42h/valaddr_rs"
keywords = ["validation", "ipv4", "ipv6", "domain"]

[dependencies]
